#!bin/bash

cd /app

if [ $NODE_ENV = "development" ]; then
  bun run vinxi dev --listen 0.0.0.0:3000
elif [ $NODE_ENV = "production" ]; then
  bun run vinxi start --listen 0.0.0.0:3000
else
  echo "Don't know how to boot a SolidStart ${NODE_ENV} environment. Exiting"
  exit 1
fi
